name: Docs

on:
  push:
    branches:        
    - main
    # Add following in for testing
    # - feature/deploy_docs

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v2
      with:
          host: github.com
          private-key: ${{ secrets.S2FFT_SECRET }}

    - name: Checkout Source
      uses: actions/checkout@v2.3.1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install package
      run: |
        cd ..
        git clone -b feature/precompute --single-branch git@github.com:astro-informatics/s2fft.git
        cd s2fft && pip install . && cd ../s2wav && pwd

        sudo apt install pandoc
        python -m pip install --upgrade pip    

        bash build_s2wav.sh

    - name: Build Documentation
      run: |
        cd docs && make html

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/_build/html # The folder the action should deploy.
