name: Tests

on:  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2.3.1
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install package
      run: |
        sudo apt install pandoc
        python -m pip install --upgrade pip    
        bash build_s2wav.sh
    
    - name: Run tests
      run: |
        pytest --cov-report term --cov=s2wav --cov-config=.coveragerc 
        codecov --token ac038325-9d87-464b-983e-a55afca9e9ce

